######################################################################
# Automatically generated by qmake (3.0) ?? 9? 3 20:47:34 2014
######################################################################

TEMPLATE = app
TARGET = big
INCLUDEPATH += .

# Input
HEADERS += getpoint.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += getpoint.cpp main.cpp mainwindow.cpp
QT += widgets